apiVersion: v1
kind: Service
metadata:
  name: {{ include "bcs-federation-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bcs-federation-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      name: metric
      port: {{ .Values.env.BK_BCS_bcsFederationManagerMetricPort }}
      targetPort: {{ .Values.env.BK_BCS_bcsFederationManagerMetricPort }}
    - protocol: TCP
      name: https
      port: {{ .Values.env.BK_BCS_bcsFederationManagerHTTPPort }}
      targetPort: {{ .Values.env.BK_BCS_bcsFederationManagerHTTPPort }}
    - protocol: TCP
      name: grpc
      port: {{ .Values.env.BK_BCS_bcsFederationManagerPort }}
      targetPort: {{ .Values.env.BK_BCS_bcsFederationManagerPort }}
  selector:
    {{- include "bcs-federation-manager.selectorLabels" . | nindent 4 }}
