{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bcs-platform-manager.confCMName" . }}
  labels:
    {{- include "bcs-platform-manager.labels" . | nindent 4 }}
data:
  conf.yaml: |-
    {{- toYaml .Values.svcConf | nindent 4 }}
{{- end }}
